### ISSUE TITLE
슬라이드 메뉴가 왼쪽에도 일부 나오는 문제.

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#17]
## Description
![image](https://user-images.githubusercontent.com/107087958/226219162-85f97599-cbcb-45e9-a44d-fe685c756825.png)

왼쪽에도 일부 나오는 문제를 해결하자.

## Todo
- [x] 원인 파악 및 문제 해결.

**Comment by robinyoon-dev** [comment]
**원인**
menu overlay의 위치.
![image](https://user-images.githubusercontent.com/107087958/226219817-f6d003e2-410d-4876-9194-23312e125f49.png)

**Comment by robinyoon-dev** [comment]
**해결**
```CSS

@media (min-width: 701px) and (max-width: 900px) {
  .grid{
    max-width: 690px;
  }
 
}
@media (min-width: 901px) and (max-width: 1024px) {
  .grid{
    max-width: 896px;
  }
}
```
grid의 max-width에 %가 아닌 절대값을 넣어주니 main의 절대 너비가 정해지면서 해결되었다.
