### ISSUE TITLE
버튼의 box-shadow부분에 커서를 올렸을 때 매우 빠른 속도로 hover와 hover가 아닌 상태가 번갈아가며 나타나는 문제

### ISSUE THREAD

**Issue by robinyoon-dev** [robinyoon-dev/plan-bingo-project#7]
## Description
https://user-images.githubusercontent.com/107087958/225466617-5e2d6e73-7cf6-458b-98b8-6fa7542d2808.mp4

유저로부터 받은 영상이다.
버튼의 box-shadow부분에 커서를 올렸을 때 매우 빠른 속도로 hover와 hover가 아닌 상태가 번갈아가며 나타나는 문제를 해결해보자.

## Todo
- [x] 문제 해결하기.

## ETC
문제 해결 과정 중 막혔을 때 이슈 제보자와 상담.

**Comment by robinyoon-dev** [comment]
# 현재 코드
```css
.button {
  padding: 1rem 1.2rem;
  border-radius: var(--border-radius);
  transition: background 200ms, border 200ms;
  display: flex;
  align-items: center;
  justify-content: center;
}

.button img {
  width: 2rem;
  height: 2rem;
  margin-right: 0.6rem;
}

.button p {
  font-size: 1.3rem;
}

/* color */
.basicColor {
  background-color: var(--btn-color);
  border: var(--border-style);
}

/* Enable hover only on non-touch devices */
@media (hover: hover) and (pointer: fine) {
  .button:hover {
    box-shadow: 10px 10px var(--color-black);
    transform: translate3d(-10px, -10px, 0);
  }
}

/* Mobile */
@media (max-width: 700px) {
  .button {
    padding: 1rem 2.5rem;
  }

  .button h2 {
    margin-bottom: 0.5rem;
  }
}

```

**Comment by robinyoon-dev** [comment]
# 해결
transition을 제대로 정해주니 문제 현상이 사라졌다.
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/4b383cf0-3294-4131-bf3d-d23db8b8de04)

추가로 버튼의 커서를 cursor:pointer로 정해줬다.
![image](https://github.com/robinyoon-dev/plan-bingo-project/assets/107087958/a33e2b59-661b-4bc7-be68-9a951ecb6895)


전체 코드
Button.module.css
```css
.button {
  padding: 1rem 1.2rem;
  border-radius: var(--border-radius);
  transition: 200ms;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}

.button img {
  width: 2rem;
  height: 2rem;
  margin-right: 0.6rem;
}

.button p {
  font-size: 1.3rem;
}

/* color */
.basicColor {
  background-color: var(--btn-color);
  border: var(--border-style);
}


/* Enable hover only on non-touch devices */
@media (hover: hover) and (pointer: fine) {
  .button:hover {
    box-shadow: 10px 10px var(--color-black);
    transform: translate3d(-10px, -10px, 0);
  }
}

/* Mobile */
@media (max-width: 700px) {
  .button {
    padding: 1rem 2.5rem;
  }

  .button h2 {
    margin-bottom: 0.5rem;
  }
}

```

이슈 영상 제공자:  @hyunbinseo

그 외 자료: [CSS로 PC와 Mobile을 구분하는 방법 - Interaction Media Features](https://paperblock.tistory.com/164)
